apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cotacao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-cotacao
  template:
    metadata:
      labels:
        app: api-cotacao
    spec:
      containers:
        - name: api-cotacao
          image: api-cotacao:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-cotacao-service
spec:
  type: NodePort
  selector:
    app: api-cotacao
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081
